<?php

// Generated from the pre-SQL implementation. Do not edit by hand.

return [
    '2026-9' => [
        'label' => 'September 2026',
        'total_sales' => 586.0,
        'order_count' => 34,
        'top_product' => 'Caipirinha',
        'average_order_value' => 17.24,
        'peak_hour' => '12:00',
    ],
    '2026-8' => [
        'label' => 'August 2026',
        'total_sales' => 2272.5,
        'order_count' => 138,
        'top_product' => 'Caipirinha',
        'average_order_value' => 16.47,
        'peak_hour' => '12:00',
    ],
    '2026-7' => [
        'label' => 'July 2026',
        'total_sales' => 100.0,
        'order_count' => 6,
        'top_product' => 'Caipirinha',
        'average_order_value' => 16.67,
        'peak_hour' => '01:00',
    ],
    '2026-6' => [
        'label' => 'June 2026',
        'total_sales' => 0,
        'order_count' => 0,
        'top_product' => null,
        'average_order_value' => 0,
        'peak_hour' => null,
    ],
    '2026-5' => [
        'label' => 'May 2026',
        'total_sales' => 0,
        'order_count' => 0,
        'top_product' => null,
        'average_order_value' => 0,
        'peak_hour' => null,
    ],
    '2026-4' => [
        'label' => 'April 2026',
        'total_sales' => 0,
        'order_count' => 0,
        'top_product' => null,
        'average_order_value' => 0,
        'peak_hour' => null,
    ],
    '2026-3' => [
        'label' => 'March 2026',
        'total_sales' => 0,
        'order_count' => 0,
        'top_product' => null,
        'average_order_value' => 0,
        'peak_hour' => null,
    ],
    '2026-2' => [
        'label' => 'February 2026',
        'total_sales' => 0,
        'order_count' => 0,
        'top_product' => null,
        'average_order_value' => 0,
        'peak_hour' => null,
    ],
    '2026-1' => [
        'label' => 'January 2026',
        'total_sales' => 0,
        'order_count' => 0,
        'top_product' => null,
        'average_order_value' => 0,
        'peak_hour' => null,
    ],
    '2025-12' => [
        'label' => 'December 2025',
        'total_sales' => 0,
        'order_count' => 0,
        'top_product' => null,
        'average_order_value' => 0,
        'peak_hour' => null,
    ],
    '2025-11' => [
        'label' => 'November 2025',
        'total_sales' => 0,
        'order_count' => 0,
        'top_product' => null,
        'average_order_value' => 0,
        'peak_hour' => null,
    ],
    '2025-10' => [
        'label' => 'October 2025',
        'total_sales' => 0,
        'order_count' => 0,
        'top_product' => null,
        'average_order_value' => 0,
        'peak_hour' => null,
    ],
];
